version: '2'

services:
  postgresql:
    image: postgres:11.5
    ports:
      - 5432:5432
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=searchneu_users

volumes:
  pg:
