name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_DB: searchneu_users
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD:
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: install node v12.16
        uses: actions/setup-node@v1
        with:
          node-version: '12.16'
      - run: yarn install
      - run: yarn test:frontend
      - run: yarn test:api
